### PR TITLE
Create help feature

### PR DESCRIPTION
**Pull request by robsonbittencourt**
Create gear structure. Add help feature.

### CODE REVIEW

**Comment by robsonbittencourt** [comment]
@robsonrosa please make the code review. Still missing the tests, when ready I will send them here, but already feedback on the code

**Comment by robsonbittencourt** [comment]
@robsonrosa I started doing the tests and falls into a problem that had left behind. I think we should inject speech.js module in hubot.js as a function. For example:
`hubot.speech().start().hello().end();`
The first solution moved the module into this project, but that does not make much sense.
What do you think?

**Comment by robsonrosa** [comment]
I like the idea of inject `speech` module in the `hubot`, but in this case we could suppress the `start` function, to use it this way:
`hubot.speech().hello().end();`
Where `speech` is a shorcut to `new Speech().start`. So, it will be able to call this:
`hubot.speech('something').end();`

**Comment by robsonbittencourt** [comment]
Done!

**Pull request merged**
